# Generated by Django 4.2.30 on 2026-06-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='meal_preference',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='plus_one',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='plus_one_meal',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='plus_one_name',
        ),
        migrations.AddField(
            model_name='rsvp',
            name='number_in_party',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='song_request',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
