# Generated by Django 4.2.30 on 2026-06-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_remove_rsvp_meal_preference_remove_rsvp_plus_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='plus_one_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
