# Generated by Django 4.2.30 on 2026-06-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_rsvp_plus_one_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='plus_one_name',
        ),
        migrations.AddField(
            model_name='rsvp',
            name='guest_names',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
