# Generated by Django 4.2.30 on 2026-06-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0004_remove_rsvp_plus_one_name_rsvp_guest_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='plus_one_dietary_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='attendance',
            field=models.CharField(choices=[('yes', 'Joyfully accepts'), ('yes_plus_one', 'Joyfully accepts with +1'), ('no', 'Regretfully declines')], max_length=13),
        ),
    ]
