# Generated by Django 4.2.30 on 2026-06-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0005_plus_one_dietary_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphoto',
            name='caption_mn',
            field=models.CharField(blank=True, max_length=300, verbose_name='Caption (Монгол)'),
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='caption_zh_hant',
            field=models.CharField(blank=True, max_length=300, verbose_name='Caption (中文)'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='attendance',
            field=models.CharField(choices=[('yes', 'Joyfully accepts'), ('no', 'Regretfully declines')], max_length=13),
        ),
    ]
